services:
  db:
    image: postgres:17-alpine
    container_name: travel_shop_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: travel
      POSTGRES_PASSWORD: travel1234
      POSTGRES_DB: travel_shop
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
